routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function () {
    return view('home');
});
Route::get('/galeryitem', function () {
    return view('item.GaleryItem');
});


Route::get('/itemGallery', 'GaleryItemController@index');
Route::get('/itemGallery/{id}', 'GaleryItemController@showedit');

Route::delete('deleteAll/supplier', 'suplierController@deleteAll');
Route::delete('deleteAll/item', 'itemController@deleteAll');


Route::get('/supplierGallery', 'supplierGalleryController@index');
Route::get('/supplierGallery/{id}', 'supplierGalleryController@showedit');
Route::get('/supplierGallery/{id}/edit', 'supplierGalleryController@edit');
Route::put('/supplierGallery/{id}', 'supplierGalleryController@update');
Route::delete('/supplierGallery/destroy/{id}', 'supplierGalleryController@destroy')->middleware('cors');

//cobain
Route::get('/testing', function(){
  return view('admin.admin_login');
});

//Admin Route Middleware
Route::match(['get', 'post'], '/admin', 'adminController@login');


Route::group(['middleware' => ['auth']],function(){

  //Admin Routes
  Route::get('/admin/dashboard','adminController@dashboard');
  Route::get('/logout','adminController@logout');
  Route::get('/admin/settings','adminController@settings');
  Route::resource('/admin/suplier', 'suplierController');
  Route::resource('/admin/item', 'itemController');
});

app/Http/Controllers/suplierController.php
<?php

namespace App\Http\Controllers;

use App\Supplier;
use DB;
use Illuminate\Http\Request;
use Session;
use Storage;
use Image;
use File;

class suplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request -> input('search');
        $supplier = Supplier::orderBy('id', 'asc')
        ->search($search)
        ->paginate(3);

        return view('/suplier/suplierView', compact('supplier', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $this -> validate($request, [
        //     'name' => 'required',
        //     'image' => 'required',
        //     'address' => 'required',
        //     'code' => 'required',
        //     'region' => 'required',
        //     'city' => 'required',
        //     'country' => 'required',
        //     'number' => 'required',
        //     'email' => 'required',
        //     'c_title' => 'required',
        //     'c_name' => 'required',
        //     'fax' => 'required'
        // ]);


        $uploadedImage = $request->file('image');
        if ($uploadedImage !== NULL) {
            $path = $this->uploadImage($request ,$uploadedImage);
        } else {
            $path = str_replace('/storage/', 'public/', $request -> input('defaultimage'));

        }
        $suppliers = new Supplier;

        $suppliers -> name = $request -> name ;
        $suppliers -> image = $path;
        $suppliers -> address = $request -> address ;
        $suppliers -> postal_code = $request -> code ;
        $suppliers -> zip_code = $request -> code ;
        $suppliers -> region = $request -> region ;
        $suppliers -> city = $request -> city ;
        $suppliers -> country = $request -> country ;
        $suppliers -> contact_phone = $request -> c_phone ;
        $suppliers -> contact_email = $request -> email ;
        $suppliers -> contact_title = $request -> c_title ;
        $suppliers -> contact_name = $request -> c_name ;
        $suppliers -> contact_fax = $request -> fax ;

        $suppliers -> save();

        return redirect()->route('suplier.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = Supplier::findOrFail($request -> id_supplier);

        $uploadedImage= $request->file('imageedit');

        if($uploadedImage !== NULL)
        {
            $old = str_replace('/storage', '', $request->image_old);
            $nama_file=Storage::url($old);
            if(File::exists('.'.$nama_file))
            {
                File::delete('.'.$nama_file);
            }
            $path   = $this->uploadImage($request ,$uploadedImage);
        }
        else{
            $path = str_replace('/storage/', 'public/', $request->image_old);

        }

        $update -> name = $request -> name ;
        $update -> image= $path;
        $update -> address = $request -> address ;
        $update -> postal_code = $request -> code ;
        $update -> zip_code = $request -> code ;
        $update -> region = $request -> region ;
        $update -> city = $request -> city ;
        $update -> country = $request -> country ;
        $update -> contact_phone = $request -> c_phone ;
        $update -> contact_email = $request -> email ;
        $update -> contact_title = $request -> c_title ;
        $update -> contact_name = $request -> c_name ;
        $update -> contact_fax = $request -> fax ;

        $update -> save();


        $id = $request -> name;

        Session::flash('u_success','Supplier ' . $id . ' Telah diperbarui.');

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Supplier::find($id);
        $defaultimage = "".$data -> image;

        switch ($defaultimage) {
            case 'public/no-image.jpg':
            $data -> delete();
            break;
            
            default:
            Storage::delete($data->image);
            $data -> delete();
            break;
        }


        return redirect()->route('suplier.index');
    }

    public function deleteAll(Request $request)
    {
        $ids = $request->ids;
        Supplier::whereIn('id',explode(",",$ids))
        ->delete();
        return response()->json(['success'=>"Produk berhasil Dihapus."]);
    }

    function uploadImage($request ,$image){
        $ext = '.'.$image->getClientOriginalExtension();
        $nama_file = $request -> input('name').$ext;

        $img = Image::make($image->getRealPath());

        $img->stream();

        $uploaded = Storage::disk('local')->put('public/supplier'.'/'.$nama_file, $img, 'public');

        $path = '';
        if($uploaded){
            $path = 'public/supplier/'.$nama_file;
        }
        return $path;
    }
}

resources/views/suplier/formsupplier.blade.php
@extends('layouts.adminLayout.admin_master')
@section('content')
<div class="main-content">
	<div class="animsition">
		<div class="container-fluid">
			<form action="{{ route('suplier.store') }}" enctype="multipart/form-data" method="POST">
				{{ csrf_field() }}
				<div class="row main-form">
					<div class="col-md-12 form">
						<div class="card">
							<div class="card-header">
								<strong>Daftar</strong>
								<small>Supplier</small>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="card-body card-block">
										<div class="form-group">
											<input type="hidden" name="id_supplier" id="supplier_id" value="">
											<label>Nama Supplier</label>
											<input type="text" name="name" id="u_name" class="form-control" placeholder="masukan nama Supplier" required="required">
										</div>
										<div class="form-group">
											<label>Gambar</label>
											<input type="file" required="required" id="imageedit" name="imageedit" accept="image/*" class="form-control" placeholder="masukan gambar">
											<input type="hidden" name="image_old" id="image_old" required="required">
											
										</div>
										<div class="form-group">
											<label>Alamat</label>
											<input type="text" name="address" id="u_address" class="form-control" placeholder="masukan alamat" required="required">
										</div>
										<div class="form-group">
											<label>Zip Code or Postal Code</label>
											<input type="text" name="code" id="u_code" class="form-control" pattern="[\d+]{5,}" maxlength="8" title="Please type your Code" placeholder="masukan Code" required="required">
											
										</div>
										<div class="form-group">
											<div class="rs-select2--light rs-select2--md">
												<select class="js-select2" name="property">
													<option selected="selected">All Properties</option>
													<option value="">Option 1</option>
													<option value="">Option 2</option>
												</select>
												<div class="dropDownSelect2"></div>
											</div>
										</div>
										<div class="form-group">
											<label>City</label>
											<input type="text" name="city" id="u_city" class="form-control" placeholder="dimana anda tinggal">

										</div>

									</div>
								</div>
								<div class="col-md-6">
									<div class="card-body card-block">
										<div class="form-group">
											<label>Nasional</label>
											<input type="text" name="country" id="u_country" class="form-control" placeholder="asal negara">
										</div>
										<div class="form-group">
											<label>Nomor Telepon</label>
											<input type="text" name="number" id="u_number" class="form-control" pattern="[\d+]{12,}" title="Please Input Your Phone Number" maxlength="13" placeholder="masukan nomer telepon anda">   

										</div>
										<div class="form-group">
											<label>Email</label>
											<input type="email" name="email" id="u_email" class="form-control" placeholder="masukan email anda">
										</div>
										<div class="form-group">

											<label>Judul Kontak</label>
											<input type="text" name="c_title" id="u_c_title" class="form-control" placeholder="judul kontak anda">
										</div>
										<div class="form-group">
											<label>Nama Kontak</label>
											<input type="text" name="c_name" id="u_c_name" class="form-control" placeholder="nama kontak anda">
										</div>
										<div class="form-group">

											<label>Fax</label>
											<input type="text" name="fax" id="u_fax" class="form-control" pattern="[\d+]{5,}" maxlength="8" placeholder="masukan Fax">
										</div>
									</div>	
								</div>
							</div>
							<div class="row">
								<div class="card-body">
									<div class="col-md-4 offset-4" style="padding-bottom: 5px;" >
										<input type="reset" name="" class="btn btn-outline-danger" style="width:250px;">                               
										<input type="submit" name="" class="btn btn-outline-primary mt-1" value="Update" style="width:250px;">
									</div>
								</div>
							</div>                                 
							<div class="col-md-4"></div>
						</div>{{-- card --}}
					</div>{{-- col-md-12 form --}}
				</div>{{-- row main-form --}}
			</form>
			<div class="row">
				<div class="col-md-12">
					<div class="copyright">
						<p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
					</div>
				</div>
			</div>
		</div>{{-- container-fluid --}}
	</div>{{-- akhir animstion --}}
</div>{{-- main content --}}
@endsection

resources/views/suplier/suplierViewDetail.blade.php
@extends('layouts.app')
@push('supplierViewDetail')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
@endpush
@section('content')
<div class="container-fluid ">
	<div class="row">
		
		<div class="col-sm-12">
			<div class="container-fluid"><ul class="nav nav-tabs">
				<li class="nav-item">
					<a class="nav-link active" href="#info">Information</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#edit">Edit</a>
				</li>				
			</ul>
			<!-- Tab panes -->
			<div class="tab-content">
				<div id="info" class="container-fluid tab-pane active"><br>
					<div class="row justify-content-center">
						<div class="col-sm-4 form-group">
							<label>Supplier</label>
							<input disabled="disabled" type="text" name="v_name" value="{{ $supplier -> name }}" class="form-control" >

							<label>Address</label>
							<input disabled="disabled" type="text" name="v_address" value="{{ $supplier -> address }}" class="form-control" >

							<label>Zip Code or Postal Code</label>
							<input disabled="disabled" type="text" name="v_code" value="{{ $supplier -> zip_code }}" class="form-control" >

							<label>Region</label>
							<input disabled="disabled" type="text" name="v_region" value="{{ $supplier -> region }}" class="form-control" >

							<label>City</label>
							<input disabled="disabled" type="text" name="v_city" value="{{ $supplier -> city }}" class="form-control" >

							<label>Country</label>
							<input disabled="disabled" type="text" name="v_country" value="{{ $supplier -> country }}" class="form-control" >
						</div>
						<div class="col-sm-4 form-group">

							<label>Phone Number</label>
							<input disabled="disabled" type="text" name="v_number" value="{{ $supplier ->  contact_phone}}" class="form-control" >

							<label>Email</label>
							<input disabled="disabled" type="email" name="v_email" value="{{ $supplier ->  contact_email}}" class="form-control" >

							<label>Contact title</label>
							<input disabled="disabled" type="text" name="v_c_title" value="{{ $supplier -> contact_title  }}" class="form-control" >

							<label>Contact Name</label>
							<input disabled="disabled" type="text" name="v_c_name" value="{{ $supplier ->  contact_name}}" class="form-control" >

							<label>Fax</label>
							<input disabled="disabled" type="text" name="v_fax" value="{{ $supplier -> contact_fax }}" class="form-control">
						</div>
						<div class="col-sm-3"><!--right col-->
							<div class="text-center">
								<img src="{{\Illuminate\Support\Facades\Storage::url($supplier->image)}}" class="img-thumbnail" alt="avatar">								
							</div>
						</div><!--/col 4-->
					</div>
				</div>
				<div id="edit" class="container-fluid tab-pane fade"><br>
					<form action="{{ route('suplier.update', 'update') }}" enctype="multipart/form-data" method="post">
						{{ method_field('patch') }}
						{{ csrf_field()}}
						<input type="hidden" name="id_supplier" value="{{ $supplier -> id }}">
						<div class="row justify-content-center">						
							<div class="col-sm-4 form-group">


								<label>Supplier</label>
								<input type="text" name="name" class="form-control" value="{{ $supplier -> name }}" placeholder="Enter Supplier">

								<label>Address</label>
								<input type="text" name="address" class="form-control" value="{{ $supplier -> address }}" placeholder="Enter Address">

								<label>Zip Code or Postal Code</label>
								<input type="text" name="code" class="form-control" pattern="[\d+]{5,}" title="Please type your Code" maxlength="8" value="{{ $supplier -> zip_code }}" placeholder="Enter Code">

								<label>Region</label>
								<input type="text" name="region" class="form-control" value="{{ $supplier -> region }}" placeholder="Enter Region">

								<label>City</label>
								<input type="text" name="city" class="form-control" value="{{ $supplier -> city }}" placeholder="Enter City">

								<label>Country</label>
								<input type="text" name="country" class="form-control" value="{{ $supplier -> country }}" placeholder="Enter Country">

							</div>
							<div class="col-sm-4 form-group">


								<label>Phone Number</label>
								<input type="text" name="number" class="form-control" pattern="[\d+]{12,}" maxlength="13" value="{{ $supplier -> contact_phone }}" placeholder="Enter The Number">

								<label>Email</label>
								<input type="email" name="email" class="form-control" value="{{ $supplier -> contact_email }}" placeholder="Enter Email">

								<label>Contact title</label>
								<input type="text" name="c_title" class="form-control" value="{{ $supplier -> contact_title }}" placeholder="Enter Contact Title">

								<label>Contact Name</label>
								<input type="text" name="c_name" class="form-control" value="{{ $supplier -> contact_name }}" placeholder="Enter Contact Name">

								<label>Fax</label>
								<input type="text" name="fax" class="form-control" pattern="[\d+]{5,}" maxlength="8" value="{{ $supplier -> contact_fax }}" placeholder="Enter Fax">

								

								<button name="clear" style="display: inline-block; margin-top: 31px;" onclick="clearForm(this.form)" class="btn btn-outline-warning" type="button"><i class="fa fa-refresh"></i> Reset</button>

								<button style="display: inline-block; margin-top: 31px;" class="btn btn-outline-primary" type="submit"><i class="fa fa-save"></i> Save</button>

								
							</div>
							<div class="col-sm-3"><!--right col-->
								<div class="text-center">
									<img id="preview" src="{{\Illuminate\Support\Facades\Storage::url($supplier->image)}}" class="avatar img-thumbnail" style="width: 100%; height: 100%;" alt="avatar">									
									<input type="file" style="display: none;" accept="image/*" id="image" name="image" class="text-center center-block">
									<input type="hidden" name="image_old" id="image_old">
									<a href="javascript:changeProfile();">Change</a> |
									<a style="color: red" href="javascript:removeImage()">Remove</a>
									<input type="hidden" style="display: none" value="0" name="remove" id="remove">
								</div>
							</div><!--/col 4-->
						</div>
					</form>
					<form action="/supplierGallery/destroy/{{ $supplier -> id }}" method="post">
						{{ csrf_field() }}
						<input type="hidden" name="_method" value="DELETE">
						<button type="submit" class="btn btn-outline-danger" style="position: absolute; left: 695px; bottom: 17px;"><i class="fa fa-trash"></i> Delete</button>
					</form>
				</div>


			</div></div>
		</div><!--/col-9-->

	</div><!--/row-->
</div>
<script>
	function clearForm(oForm) {

		var elements = oForm.elements; 

		oForm.reset();

		for(i=0; i<elements.length; i++) {

			field_type = elements[i].type.toLowerCase();

			switch(field_type) {

				case "text": 
				case "email":
				elements[i].value = ""; 
				break;

				default: 
				break;
			}
		}
	}

	function changeProfile() {
		$('#image').click();
	}
	$('#image').change(function () {
		var imgPath = $(this)[0].value;
		var ext = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
		if (ext == "gif" || ext == "png" || ext == "jpg" || ext == "jpeg") {
			readURL(this);
		}
		else {
			alert("Please select image file (jpg, jpeg, png).");
			$('#image').val("");
		}
			
	});
	function readURL(input) {
		if (input.files && input.files[0]) {
			var reader = new FileReader();
			reader.readAsDataURL(input.files[0]);
			reader.onload = function (e) {
				$('#preview').attr('src', e.target.result);
				$('#remove').val(0);
			}
		}
	}
	function removeImage() {
		$('#preview').attr('src', '{{\Illuminate\Support\Facades\Storage::url($supplier->image)}}');
		$('#remove').val(1);
	}

	$(document).ready(function() {

		$(".nav-tabs a").click(function(){
			$(this).tab('show');
		});
	});
</script>   
@endsection